# Generated by Django 4.2.6 on 2023-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_historicalorder_historicalcourse_historicalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
