# Generated by Django 4.2.6 on 2023-10-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_start_date_historicalcourse_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',)},
        ),
    ]
