# Generated by Django 4.2.6 on 2023-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('cancelled', 'Canceled'), ('pending', 'Pending'), ('pop', 'Pop')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('cancelled', 'Canceled'), ('pending', 'Pending'), ('pop', 'Pop')], default='pending', max_length=10),
        ),
    ]
