# Generated by Django 4.2.6 on 2023-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historicalorder_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('cancelled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('cancelled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
