# Generated by Django 4.2.6 on 2023-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_dob_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
