# Generated by Django 4.2.6 on 2023-11-02 09:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_proofofpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofofpayment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 11, 6))]),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='file',
            field=models.FileField(upload_to='proof_of_payments'),
        ),
    ]
