# Generated by Django 4.2.6 on 2023-11-03 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_dob_historicalproofofpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproofofpayment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ProofOfPaymentReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('pop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.proofofpayment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
