# Generated by Django 4.2.6 on 2023-11-07 08:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_historicalproofofpayment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproofofpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalproofofpayment',
            name='file',
            field=models.TextField(help_text='Accepted File Formats: We accept the following file formats: PDF, JPG, PNG.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 11, 11))]),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='file',
            field=models.FileField(help_text='Accepted File Formats: We accept the following file formats: PDF, JPG, PNG.', upload_to='proof_of_payments'),
        ),
    ]
