# Generated by Django 4.2.6 on 2023-11-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_historicalproofofpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproofofpayment',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
