# Generated by Django 4.2.6 on 2023-11-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_historicalorder_status_alter_order_status'),
        ('accounts', '0017_alter_historicalproofofpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproofofpayment',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.order'),
        ),
        migrations.AddField(
            model_name='proofofpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order'),
        ),
    ]
