# Generated by Django 4.2.6 on 2023-11-08 13:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_historicalproofofpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproofofpayment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Actioned', 'Actioned')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2007, 11, 12))]),
        ),
        migrations.AlterField(
            model_name='proofofpayment',
            name='status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Actioned', 'Actioned')], default='Pending', max_length=20),
        ),
    ]
