from django.urls import path
from .views import (
    NewCategoryView, NewCourseView, NewLessonView,
    NewTopicView, CourseListView, InstructorCourseListView,
    EditCourseView, CourseTopicListView, TopicLessonListView,
    EditLessonView, EditTopicView, CourseDetailView, OrderDetailView, OrdersView,
    EnrollStudentsView, enroll_student, delete_course, payment_return, initiate_payment, delete_order, add_to_cart,
    export_orders_table, ReportsView, students_enrolled_by_gender, enroll_student
)


app_name = "app"
urlpatterns = [
    path('', CourseListView.as_view(), name="index"),
    path('paynow/return/',
         payment_return, name='payment_return'),
    # path('paynow/success/', payment_callback, name='payment_success'),
    path('orders/', OrderDetailView.as_view(), name="user_orders"),
    path('reports/', ReportsView.as_view(), name="reports"),
    path('reports/students_enrolled_by_gender',
         students_enrolled_by_gender, name="students_enrolled_by_gender"),
    path('all-orders/', OrdersView.as_view(), name="orders"),
    path('all-orders/export', export_orders_table, name="export_orders"),
    path('orders/<int:course_id>/delete', delete_order, name="delete_order"),
    path('courses/<int:course_id>/add-to-cart',
         add_to_cart, name="add_to_cart"),
    path('courses/', InstructorCourseListView.as_view(), name="instructor_courses"),
    path('courses/<int:id>/', CourseDetailView.as_view(), name="course_detail"),
    path('courses/<int:course_id>/enroll', enroll_student, name="enroll"),
    path('courses/<int:course_id>/delete',
         delete_course, name="delete_course"),
    path('courses/<int:course_id>/learn',
         enroll_student, name="enroll_student"),
    path('orders/initiate_payment/',
         initiate_payment, name="initiate_payment"),
    path('courses/<int:id>/topics/',
         CourseTopicListView.as_view(), name="course_topics"),
    path('courses/<int:id>/enroll/',
         EnrollStudentsView.as_view(), name="enroll_students"),
    path('courses/<int:id>/topics/<int:pk>/edit',
         EditTopicView.as_view(), name="edit_topic"),
    path('courses/<int:id>/topics/<int:pk>/lessons/',
         TopicLessonListView.as_view(), name="topic_lessons"),
    path('courses/<int:id>/topics/<int:pk>/lessons/<int:lesson_id>/edit',
         EditLessonView.as_view(), name="edit_lessons"),
    path('courses/<int:course_id>/edit/',
         EditCourseView.as_view(), name="edit_course"),
    path('courses/new_course/', NewCourseView.as_view(), name="new_course"),
    path('categories/new_category/',
         NewCategoryView.as_view(), name="new_category"),
    path('courses/<int:id>/topics/new_topic/',
         NewTopicView.as_view(), name="new_topic"),
    path('courses/<int:id>/topics/<int:pk>/new_lesson/',
         NewLessonView.as_view(), name="new_lesson"),
]
